SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Ordenar números hasta 100', '', 'publish', 'closed', 'closed', '', 'ordenar-numeros-hasta-100', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Ordenar números de dos cifras|Comparar decenas|Usar secuencia numérica ampliada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Lee los números|Ordénalos de menor a mayor|Verifica tu respuesta');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 23, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 14, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 60, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Comparar números hasta 100', '', 'publish', 'closed', 'closed', '', 'comparar-numeros-hasta-100', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Comparar números de dos cifras|Usar símbolos <, >, =|Razonar con decenas');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Compara los números|Piensa en las decenas primero|Elige el símbolo correcto');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 23, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 14, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 61, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Problemas de suma', '', 'publish', 'closed', 'closed', '', 'problemas-de-suma', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '25');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Resolver problemas verbales|Identificar datos relevantes|Aplicar sumas');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Lee el problema con atención|Identifica qué operación necesitas|Resuelve y elige la respuesta');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 40, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 14, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 61, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Problemas de resta', '', 'publish', 'closed', 'closed', '', 'problemas-de-resta', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '25');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Resolver problemas de resta|Comprender situaciones de pérdida|Razonar lógicamente');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Lee el problema despacio|Piensa qué información es importante|Calcula y responde');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 40, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 14, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 52, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Problemas mixtos', '', 'publish', 'closed', 'closed', '', 'problemas-mixtos', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '30');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Identificar operación necesaria|Resolver problemas de suma y resta|Razonar de forma autónoma');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Lee con mucha atención|Decide si es suma o resta|Resuelve y verifica');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 40, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 14, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 52, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Reconocer formas básicas', '', 'publish', 'closed', 'closed', '', 'reconocer-formas-basicas', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '15');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Identificar círculo, cuadrado, triángulo|Nombrar formas geométricas|Reconocer en contexto');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Observa cada forma|Identifica su nombre|Selecciona la respuesta correcta');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 27, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 28, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 59, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Contar lados y vértices', '', 'publish', 'closed', 'closed', '', 'contar-lados-y-vertices', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Contar lados de figuras|Identificar vértices|Clasificar por número de lados');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Cuenta los lados de la figura|Cuenta los vértices (esquinas)|Responde las preguntas');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 27, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 28, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 60, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Clasificar figuras', '', 'publish', 'closed', 'closed', '', 'clasificar-figuras', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Clasificar figuras por características|Identificar similitudes|Agrupar formas');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Observa las características|Agrupa las figuras similares|Elige la clasificación correcta');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 27, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 28, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 61, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Comparar tamaños', '', 'publish', 'closed', 'closed', '', 'comparar-tamanos', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '15');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Comparar objetos por tamaño|Usar términos: grande, pequeño, mediano|Ordenar por tamaño');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Observa los objetos|Compara sus tamaños|Ordénalos de menor a mayor');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 41, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 15, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Medir con objetos', '', 'publish', 'closed', 'closed', '', 'medir-con-objetos', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Medir longitud con unidades no estándar|Comparar longitudes|Contar unidades');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Cuenta cuántos clips mide el objeto|Compara las medidas|Responde correctamente');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 41, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 60, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Comparar pesos', '', 'publish', 'closed', 'closed', '', 'comparar-pesos', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Comparar objetos por peso|Usar términos: pesado, ligero|Ordenar por peso');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Imagina el peso de cada objeto|Piensa cuál pesa más|Ordena de ligero a pesado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 41, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 61, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Las horas en punto', '', 'publish', 'closed', 'closed', '', 'las-horas-en-punto', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Leer horas en punto|Identificar manecillas del reloj|Reconocer horario');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Observa las manecillas|La pequeña marca la hora|Identifica qué hora es');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 42, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 15, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Las medias horas', '', 'publish', 'closed', 'closed', '', 'las-medias-horas', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '25');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Leer horas y medias|Identificar :30 minutos|Usar terminología "y media"');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Mira dónde apuntan las manecillas|Si la larga está en el 6, son "y media"|Selecciona la hora correcta');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 42, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 60, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Ordenar momentos del día', '', 'publish', 'closed', 'closed', '', 'ordenar-momentos-del-dia', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '15');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Secuenciar eventos diarios|Usar términos: mañana, tarde, noche|Comprender orden temporal');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Lee las actividades|Piensa en cuándo las haces|Ordénalas correctamente');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 42, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 15, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Antes, durante y después', '', 'publish', 'closed', 'closed', '', 'antes-durante-y-despues', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '20');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Usar conceptos temporales|Identificar secuencia de eventos|Razonar temporalmente');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Lee la situación|Piensa qué ocurre antes, durante o después|Selecciona la respuesta');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 42, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 60, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Reconocer monedas', '', 'publish', 'closed', 'closed', '', 'reconocer-monedas', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '15');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Identificar monedas de euro|Reconocer valores: 1€, 2€, 5€|Nombrar monedas');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Observa cada moneda|Lee su valor|Identifícala correctamente');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 43, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 15, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Sumar cantidades de dinero', '', 'publish', 'closed', 'closed', '', 'sumar-cantidades-de-dinero', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '25');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Sumar monedas|Calcular totales|Resolver problemas con dinero');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Suma el valor de las monedas|Calcula el total|Selecciona la respuesta correcta');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 43, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 61, 0);
INSERT INTO mzvw_posts (post_author, post_date, post_date_gmt, post_content, post_title, post_excerpt, post_status, comment_status, ping_status, post_password, post_name, to_ping, pinged, post_modified, post_modified_gmt, post_content_filtered, post_parent, guid, menu_order, post_type, post_mime_type, comment_count) VALUES (1, NOW(), UTC_TIMESTAMP(), '', 'Problemas con dinero', '', 'publish', 'closed', 'closed', '', 'problemas-con-dinero', '', '', NOW(), UTC_TIMESTAMP(), '', 0, '', 0, 'ficha', '', 0);
SET @post_id = LAST_INSERT_ID();
UPDATE mzvw_posts SET guid = CONCAT('http://localhost:8080/?post_type=ficha&p=', @post_id) WHERE ID=@post_id;
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'edad_recomendada', '6-7 años');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_edad_recomendada', 'field_edad_recomendada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'tiempo_estimado', '30');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_tiempo_estimado', 'field_tiempo_estimado');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'destacada', '0');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_destacada', 'field_destacada');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'objetivos', 'Resolver situaciones de compra|Calcular cambio|Aplicar sumas y restas con dinero');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_objetivos', 'field_objetivos');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'instrucciones', 'Lee el problema con atención|Identifica qué operación necesitas|Calcula y responde');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_instrucciones', 'field_instrucciones');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, 'descripcion', '');
INSERT INTO mzvw_postmeta (post_id, meta_key, meta_value) VALUES (@post_id, '_descripcion', 'field_descripcion');
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 11, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 31, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 10, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 43, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 30, 0);
INSERT INTO mzvw_term_relationships (object_id, term_taxonomy_id, term_order) VALUES (@post_id, 52, 0);
UPDATE mzvw_term_taxonomy tt SET tt.count = (SELECT COUNT(*) FROM mzvw_term_relationships tr WHERE tr.term_taxonomy_id = tt.term_taxonomy_id) WHERE tt.term_taxonomy_id IN (10,11,14,15,23,27,28,30,31,40,41,42,43,52,59,60,61);
COMMIT;

